//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Trezorix")]
[assembly: AssemblyCopyright("Trezorix")]
[assembly: AssemblyProduct("Trezorix Checkers 2")]
[assembly: AssemblyVersion("2.4.527")]
[assembly: AssemblyInformationalVersion("2")]


